#!/usr/bin/env php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

/* (C) 2015 Romain "Artefact2" Dal Maso <artefact2@gmail.com> */

require __DIR__.'/markdown.php';
require __DIR__.'/easydom.php';

function fatal($test, $message) {
	global $argv;
    
	if($test) {
		fprintf(STDERR, "{$argv[0]}: ".$message."\n");
		die(1);
	}
}

fatal($argc !== 3, "Usage: {$argv[0]} <input-md> <output-xhtml>");
list($me, $in, $out) = $argv;

$mdin = file_get_contents($in);
fatal($mdin === false, "cannot read input md file $in.");

list($rawhdr, $md) = explode("\n\n", $mdin, 2);
$headers = [];

foreach(explode("\n", $rawhdr) as $hline) {
	list($k, $v) = explode(': ', $hline, 2);
	$headers[$k] = $v;
}

fatal(!isset($headers['Type']), "input md file has no Type header.");

switch($headers['Type']) {

case 'page':
	$p = new \EasyDOM\Document();
	$html = $p->element('html', [ 'xmlns' => 'http://www.w3.org/1999/xhtml' ]);
	$head = $html->appendCreate('head');
	$body = $html->appendCreate('body');

	$head->appendCreate('link', [
		'rel' => 'stylesheet',
		'type' => 'text/css',
		'href' => 't.css',
	]);
	$head->appendCreate('title', $title = (isset($headers['Title']) ? $headers['Title'] : 'Unnamed page'));

	$wrap = $body->appendCreate('div#wrap');
	$wrap->appendCreate('header')->appendCreate('h1', $title);

	$frag = $p->createDocumentFragment();
	$frag->appendXML(Markdown($md));
	$wrap->append($frag);

	$p->appendChild($html);
	fatal($p->save($out) === false, "could not write to output file $out.");
	break;
	
default:
	fatal(true, "input md file has unknown type {$headers['Type']}.");
	
}

die(0);
